version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/resume_ai
      - SECRET_KEY=b37985b84e73c3f05b105c318b6cee4f819d8b73396a08710b12aaade300cda7
      - ENVIRONMENT=production
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=resume_ai
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
